from .employees.employee_list import employee_list
from .employees.employee_form import employee_form
from .training_programs.training_list import training_list
from .training_programs.training_form import training_form
from .training_programs.program_details import program_details
from .training_programs.past_programs import past_programs
from .computers.computer_list import computer_list
from .computers.computer_form import computer_form
from .computers.computer_details import computer_details
from .home import home
from .auth.logout import logout_user
from .connection import Connection
from .departments.list import department_list
from .computers.computer_form import computer_form
from .departments.form import department_form
from .departments.details import department_details
