from .employees.employee_list import employee_list
from .employees.employee_form import employee_form
from .employees.details import employee_details
from .training_programs.training_list import training_list
from .computers.computer_list import computer_list
from .computers.computer_form import computer_form
from .home import home
from .auth.logout import logout_user
from .connection import Connection
from .departments.list import department_list
from .computers.computer_form import computer_form
from .departments.form import department_form
from .departments.details import department_details
